name: Build

on:
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install And Build
      run: |
        npm i
        npm i ts-node -g
        npm run build
        cat packages/yovolve/dist/index.html
    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: packages/yovolve/dist
    - name: Publish Packages to NPM
      if: ${{ github.event_name == 'push' }}
      run: ts-node scripts/publish.ts
      env:
        NPM_SECRET: ${{ secrets.NPM_SECRET }}