name: CI

on:
  push:
    branches:    
      - main
  pull_request:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Publish packages to NPM
      if: ${{ github.event_name == 'push' }}
      run: ts-node scripts/publish.ts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}